### ISSUE TITLE
Error loading topics.json

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#175]
```
Traceback (most recent call last):
  File "/usr/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 191, in command
    fetch_callback(consumer, method, header, body)
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/queue.py", line 407, in fetch_callback
    fetch_and_import_stages(harvester, obj)
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/queue.py", line 424, in fetch_and_import_stages
    success_import = harvester.import_stage(obj)
  File "/usr/lib/ckan/default/src/ckanext-dcatapit/ckanext/dcatapit/harvesters/ckanharvester.py", line 22, in import_stage
    map_nonconformant_groups(harvest_object)
  File "/usr/lib/ckan/default/src/ckanext-dcatapit/ckanext/dcatapit/mapping.py", line 99, in map_nonconformant_groups
    themes_data = _load_mapping_data()
  File "/usr/lib/ckan/default/src/ckanext-dcatapit/ckanext/dcatapit/mapping.py", line 71, in _load_mapping_data
    map_data = handler(f)
  File "/usr/lib/ckan/default/src/ckanext-dcatapit/ckanext/dcatapit/mapping.py", line 30, in _map_themes_json
    data = json.load(fdesc)
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 7: invalid continuation byte
```

**Comment by etj** [comment]
This is fixed by adding the `encoding` param in `json.load()`:
```
def _map_themes_json(fdesc):
    data = json.load(fdesc, encoding='latin-1')
    out = {}
    for map_item in data['data']:
```

Should we parametrize the encoding?

**Comment by etj** [comment]
Let catch the UnicodeDecodeError for utf8, then use as fallback 'latin-1', else skip the file parsing.
