### ISSUE TITLE
Error when harvesting dataset with same title

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#176]
The source catalog contains:
![milano_dup](https://user-images.githubusercontent.com/717359/37917356-80e4b434-311e-11e8-9e3d-77ed9341cb93.png)

In the harvester we get this error:
```
Error importing dataset turismo-presenze-nelle-strutture-ricettive-per-provenienza: IntegrityError('(IntegrityError) duplicate key value violates unique constraint "package_name_key"\nDETAIL: Key (name)=(turismo-presenze-nelle-strutture-ricettive-per-provenienza) already exists.\n',) /
 Traceback (most recent call last): 
File "/usr/lib/ckan/default/src/ckanext-dcat/ckanext/dcat/harvesters/rdf.py", line 378, in import_stage p.toolkit.get_action('package_create')(context, dataset) 
File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 431, in wrapped result = _action(context, data_dict, **kw) 
File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 187, in package_create pkg = model_save.package_dict_save(data, context) 
File "/usr/lib/ckan/default/src/ckan/ckan/lib/dictization/model_save.py", line 303, in package_dict_save package_membership_list_save(pkg_dict.get("groups"), pkg, context) 
File "/usr/lib/ckan/default/src/ckan/ckan/lib/dictization/model_save.py", line 225, in package_membership_list_save model.Session.flush() 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 149, in do return getattr(self.registry(), name)(*args, **kwargs) 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1907, in flush self._flush(objects) 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2025, in _flush transaction.rollback(_capture_exception=True) 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 57, in __exit__ compat.reraise(exc_type, exc_value, exc_tb) 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1989, in _flush flush_context.execute() 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 371, in execute rec.execute(self) 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 524, in execute uow
File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 64, in save_obj mapper, table, insert) 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 568, in _emit_insert_statements execute(statement, multiparams) 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 727, in execute return meth(self, multiparams, params) 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection return connection._execute_clauseelement(self, multiparams, params) 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 824, in _execute_clauseelement compiled_sql, distilled_params 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context context) 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception exc_info 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause reraise(type(exception), exception, tb=exc_tb) 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context context) 
File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute cursor.execute(statement, parameters) IntegrityError: (IntegrityError) duplicate key value violates unique constraint "package_name_key" DETAIL: Key (name)=(turismo-presenze-nelle-strutture-ricettive-per-provenienza) already exists. 'INSERT INTO package (id, name, title, version, url, author, author_email, maintainer, maintainer_email, notes, license_id, type, owner_org, creator_user_id, metadata_created, metadata_modified, private, state, revision_id) VALUES (%(id)s, %(name)s, %(title)s, %(version)s, %(url)s, %(author)s, %(author_email)s, %(maintainer)s, %(maintainer_email)s, %(notes)s, %(license_id)s, %(type)s, %(owner_org)s, %(creator_user_id)s, %(metadata_created)s, %(metadata_modified)s, %(private)s, %(state)s, %(revision_id)s)' {'maintainer': None, 'name': u'turismo-presenze-nelle-strutture-ricettive-per-provenienza', 'metadata_modified': datetime.datetime(2018, 3, 26, 15, 34, 47, 960862), 'title': u'Turismo: presenze nelle strutture ricettive per provenienza', 'author_email': None, 'notes': u'Il dataset contiene i dati sul flusso di turisti nelle strutture ricettive di Milano, distinti per paese/area di provenienza. Per "presenze" si intende il numero di notti trascorse dai clienti negli esercizi ricettivi nel periodo considerato. I dati sono disponibili dal 2000 al 2015, ma con diversi livelli di disaggregazione che riflettono i mutamenti geopolitici intercorsi negli anni (in particolare per l\'area UE). Per garantire il massimo livello di dettaglio e una corretta lettura dei dati sono state create due diverse serie storiche (dal 2000 al 2004 e dal 2005 al 2015). FONTE: Elaborazioni Provincia di Milano in attesa di validazione ISTAT.\r\n', 'owner_org': u'58e5c521-a2f0-4694-9b07-fb744220cf21', 'private': False, 'maintainer_email': None, 'url': u'http://dati.comune.milano.it/dataset/ds213-turismotempolibero-strutture-ricettive-presenze-provenienza-2005-2015', 'state': u'active', 'version': None, 'author': None, 'creator_user_id': u'c690c09b-0f24-4fa0-a9bd-094ffc5bd824', 'license_id': u'Creative Commons Attribuzione Italia 3.0 (CC BY 3.0 IT)', 'revision_id': u'da54f1ce-e687-4f99-bc86-f061fdbd48a9', 'type': u'dataset', 'id': u'baecd65b-690c-4576-a69d-0c51a448a222', 'metadata_created': datetime.datetime(2018, 3, 26, 15, 34, 47, 960851)}
```

**Comment by cezio** [comment]
Can't reproduce. I was checking https://dati.comune.milano.it/catalog.rdf, got all data imported without an error. Used master latest branch (with recent fixes).

![image](https://user-images.githubusercontent.com/116021/37962686-2e5a5518-31bc-11e8-8a69-afc15f2b147e.png)
