### ISSUE TITLE
Error in command "vocabulary initdb"

### ISSUE THREAD

**Issue by AzzurraP** [geosolutions-it/ckanext-dcatapit#233]
Error in initdb vocabulary
>paster --plugin=ckanext-dcatapit vocabulary initdb --config=/etc/ckan/default/production.ini
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 101, in run
    command = commands[command_name].load()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2305, in load
    return self.resolve()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2311, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/ckan/default/src/ckanext-dcatapit/ckanext/dcatapit/commands/dcatapit.py", line 14, in <module>
    from ckan.logic.schema import tag_name_validator
ImportError: cannot import name tag_name_validator

Temporary fix in /usr/lib/ckan/default/src/ckanext-dcatapit/ckanext/dcatapit/commands/dcatapit.py", line 14:

from ckan.logic.validators import tag_name_validator

**Comment by tdipisa** [comment]
@AzzurraP, thank you for reporting this.
Please, can you specify the CKAN version you are using?

**Comment by AzzurraP** [comment]
Yes of course , it's  2.8.1 version
