### ISSUE TITLE
ckan 2.8 compatibility

### ISSUE THREAD

**Issue by cezio** [geosolutions-it/ckanext-dcatapit#237]
I briefly checked dcatapit compatibility with ckan 2.8. In general,it works:

* catalog.rdf/jsonld export works
* dcat rdf harvester works
* ckan-dcatapit harvester works

 except for:

 * minor bug in themes to groups mapping (fixed by https://github.com/cezio/ckanext-dcatapit/commit/e96ed2559fabdb88e799d8d83fe1401e5a0c938d)

 * minor layout problems (wrong input sizes, elements bad alignment, missing glyph icons) in organization form:

![image](https://user-images.githubusercontent.com/116021/46734357-3a967d80-cc93-11e8-9c97-c76f00ca6786.png)

![image](https://user-images.githubusercontent.com/116021/46734386-54d05b80-cc93-11e8-8e3e-07b4d90de272.png)

![image](https://user-images.githubusercontent.com/116021/46734424-6fa2d000-cc93-11e8-9382-0a18430429b0.png)

* fields in tabs are not displayed correclty (some are repeated in each tab)
* can't edit editor field

* dcatapit csw works partially - multilang causes exception (even if it's not in plugins list):

2018-10-10 11:26:33,937 ERROR [ckanext.multilang.model.package_multilang] Exception occurred while persisting DB objects: (psycopg2.IntegrityError) BŁĄD:  pusta wartość w kolumnie "text" narusza ograniczenie wymaganej wartości
DETAIL:  Niepoprawne ograniczenia wiersza (5329, 8ae49e63-df5e-40c0-a7bf-59d8f3c974af, publisher_name, extra, en, null).
 [SQL: 'INSERT INTO package_multilang (package_id, field, field_type, lang, text) VALUES (%(package_id)s, %(field)s, %(field_type)s, %(lang)s, %(text)s) RETURNING package_multilang.id'] [parameters: {'lang': 'en', 'field': u'publisher_name', 'package_id': u'8ae49e63-df5e-40c0-a7bf-59d8f3c974af', 'text': None, 'field_type': 'extra'}]
Traceback (most recent call last):
  File "/home/cezio/.virtualenvs/ckan-2.8/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/mnt/work/cezio/geosolutions/repos/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 193, in command
    fetch_callback(consumer, method, header, body)
  File "/mnt/work/cezio/geosolutions/repos/ckanext-harvest/ckanext/harvest/queue.py", line 407, in fetch_callback
    fetch_and_import_stages(harvester, obj)
  File "/mnt/work/cezio/geosolutions/repos/ckanext-harvest/ckanext/harvest/queue.py", line 424, in fetch_and_import_stages
    success_import = harvester.import_stage(obj)
  File "/mnt/work/cezio/geosolutions/repos/ckanext-spatial/ckanext/spatial/harvesters/base.py", line 609, in import_stage
    package_id = p.toolkit.get_action('package_create')(context, package_dict)
  File "/mnt/work/cezio/geosolutions/repos/ckan-2.8/ckan/logic/__init__.py", line 464, in wrapped
    result = _action(context, data_dict, **kw)
  File "/mnt/work/cezio/geosolutions/repos/ckan-2.8/ckan/logic/action/create.py", line 211, in package_create
    item.after_create(context, data)
  File "/mnt/work/cezio/geosolutions/repos/ckanext-dcatapit/ckanext/dcatapit/plugin.py", line 305, in after_create
    self.create_loc_field(extra, lang, pkg_dict.get('id'))
  File "/mnt/work/cezio/geosolutions/repos/ckanext-dcatapit/ckanext/dcatapit/plugin.py", line 468, in create_loc_field
    interfaces.save_extra_package_multilang({'id': pkg_id, 'text': extra.get('value'), 'field': extra.get('key')}, lang, 'extra')
  File "/mnt/work/cezio/geosolutions/repos/ckanext-dcatapit/ckanext/dcatapit/interfaces.py", line 83, in save_extra_package_multilang
    PackageMultilang.persist(pkg, lang, field_type)
  File "/mnt/work/cezio/geosolutions/repos/ckanext-multilang/ckanext/multilang/model/package_multilang.py", line 151, in persist
    session.commit()
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 430, in _prepare_impl
    self.session.dispatch.before_commit(self.session)
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
    fn(*args, **kw)
  File "/mnt/work/cezio/geosolutions/repos/ckan-2.8/ckan/model/meta.py", line 55, in before_commit
    session.flush()
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2255, in _flush
    flush_context.execute()
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/cezio/.virtualenvs/ckan-2.8/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) BŁĄD:  pusta wartość w kolumnie "text" narusza ograniczenie wymaganej wartości
DETAIL:  Niepoprawne ograniczenia wiersza (5329, 8ae49e63-df5e-40c0-a7bf-59d8f3c974af, publisher_name, extra, en, null).
 [SQL: 'INSERT INTO package_multilang (package_id, field, field_type, lang, text) VALUES (%(package_id)s, %(field)s, %(field_type)s, %(lang)s, %(text)s) RETURNING package_multilang.id'] [parameters: {'lang': 'en', 'field': u'publisher_name', 'package_id': u'8ae49e63-df5e-40c0-a7bf-59d8f3c974af', 'text': None, 'field_type': 'extra'}]

**Comment by tdipisa** [comment]
This issue is out of date.
