### ISSUE TITLE
Error retrieving organization via API

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#291]
When an organization is retrieved, using the call `api/3/action/organization_show?id=ORGANIZATION_ID&include_datasets=false`, a response 500 is returned, and the server logs this error:
```
2022-05-06 17:16:42,198 ERROR [ckan.config.middleware.flask_app] <ckan.lib.navl.dictization_functions.Missing object at 0x7f305ff1d520> is not JSON serializable
Traceback (most recent call last):
  File "/home/geosol/prj/ckan/29_dcat/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geosol/prj/ckan/29_dcat/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/ssd2/homeext/geosol/prj/ckan/29_dcat/ckan/ckan/config/middleware/../../views/api.py", line 353, in action
    return _finish_ok(return_dict)
  File "/mnt/ssd2/homeext/geosol/prj/ckan/29_dcat/ckan/ckan/config/middleware/../../views/api.py", line 112, in _finish_ok
    return _finish(status_int, response_data, content_type, headers)
  File "/mnt/ssd2/homeext/geosol/prj/ckan/29_dcat/ckan/ckan/config/middleware/../../views/api.py", line 66, in _finish
    response_msg = json.dumps(
  File "/home/geosol/prj/ckan/29_dcat/venv/lib/python3.8/site-packages/simplejson/__init__.py", line 383, in dumps
    return cls(
  File "/home/geosol/prj/ckan/29_dcat/venv/lib/python3.8/site-packages/simplejson/encoder.py", line 291, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/geosol/prj/ckan/29_dcat/venv/lib/python3.8/site-packages/simplejson/encoder.py", line 373, in iterencode
    return _iterencode(o, 0)
  File "/home/geosol/prj/ckan/29_dcat/venv/lib/python3.8/site-packages/simplejson/encoder.py", line 268, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <ckan.lib.navl.dictization_functions.Missing object at 0x7f305ff1d520> is not JSON serializable
```

**Comment by etj** [comment]
This error only happens when `dcatapit_org` is declared in the plugins list.
