### ISSUE TITLE
Error running initdb with Ckan 2.10

### ISSUE THREAD

**Issue by filos1983** [geosolutions-it/ckanext-dcatapit#297]
Hello, I'm trying to install this plu-in in my CKAN 2.10 instance but I receive an error running initdb (point 10 in installation guide):

```
$ ckan --config=/etc/ckan/default/ckan.ini dcatapit initdb
2023-09-08 15:43:22,260 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2023-09-08 15:43:22,260 INFO  [ckan.config.environment] Loading static files from public
2023-09-08 15:43:22,446 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 33, in <module>
    sys.exit(load_entry_point('ckan', 'console_scripts', 'ckan')())
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 121, in parse_args
    result = super().parse_args(ctx, args)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1613, in parse_args
    rest = super().parse_args(ctx, args)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/click/core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 131, in _init_ckan_config
    _add_ctx_object(ctx, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 140, in _add_ctx_object
    ctx.obj = CtxObject(path)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 57, in __init__
    self.app = make_app(raw_config)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 27, in make_app
    load_environment(conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 69, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 224, in load_all
    load(*plugins)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 240, in load
    service = _get_service(plugin)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 347, in _get_service
    return plugin.load()(name=plugin_name)
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2465, in load
    return self.resolve()
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2471, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/ckan/default/src/ckanext-dcatapit/ckanext/dcatapit/plugin.py", line 12, in <module>
    import ckanext.dcatapit.helpers as helpers
  File "/usr/lib/ckan/default/src/ckanext-dcatapit/ckanext/dcatapit/helpers.py", line 14, in <module>
    import ckanext.dcatapit.interfaces as interfaces
  File "/usr/lib/ckan/default/src/ckanext-dcatapit/ckanext/dcatapit/interfaces.py", line 7, in <module>
    from ckan.lib.base import model
ImportError: cannot import name 'model' from 'ckan.lib.base' (/usr/lib/ckan/default/src/ckan/ckan/lib/base.py)

```
Is dcatapit compatible with 2.10? Is there something I can check to solve the issue?

Thanks

**Comment by etj** [comment]
As stated in the README, currently this extension is only compatible with CKAN 2.9.
Please follow #300 for any advancement on 2.10 compatibility.
